@echo off
echo Starting Backend...
start cmd /k "cd Backend && npm run dev"

echo Starting Frontend...
start cmd /k "cd Frontend && npm run dev"

echo Starting Cloudflare Tunnel for Frontend...
start cmd /k "cloudflared tunnel --url http://localhost:5173"

echo Interview Master services are starting in new windows...
