const resume = `Arjun Mehta is a motivated and detail-oriented Full Stack Developer currently pursuing a Bachelor of Technology in Information Technology from Silver Oak University with a CGPA of 8.9. He has strong knowledge of frontend and backend web development technologies including HTML, CSS, JavaScript, React.js, Node.js, Express.js, MongoDB, Firebase, and REST APIs. Arjun has developed multiple real-world projects such as an Interview Master Portal for mock interviews and AI-based feedback, an AI Resume Analyzer that compares resumes with job descriptions and provides ATS suggestions, and a responsive E-Commerce platform with payment integration and admin dashboard features. He has also completed a Frontend Developer internship at TechNova Solutions where he worked on reusable React components, API integrations, and responsive UI optimization. Along with project experience, he has earned certifications from IBM SkillsBuild, AWS, and Mastercard Cybersecurity programs. Arjun is passionate about problem-solving, software engineering, and continuously learning new technologies to build scalable and impactful digital products.`


const jobDescription = `Infosys is hiring an Associate Full Stack Developer to join its engineering team. The company is looking for candidates with strong knowledge of web development technologies and good problem-solving abilities. The ideal candidate should have experience with HTML, CSS, JavaScript, React.js or Angular, and backend technologies such as Node.js or Java. Applicants should understand REST APIs, database systems, Git, and software development best practices. The selected candidate will be responsible for developing scalable web applications, collaborating with cross-functional teams, debugging and optimizing applications, writing clean and reusable code, and participating in agile development workflows. Good communication skills, teamwork, and a willingness to learn modern technologies are essential for this role. The position is full-time and based in Bangalore with an offered salary range between 4 LPA and 7 LPA.`


const selfDescription = `Hello, my name is Arjun Mehta, and I am currently pursuing my B.Tech in Information Technology. I am passionate about full-stack web development and enjoy creating applications that solve real-world problems. Over the past few years, I have worked on several projects using React.js, Node.js, MongoDB, and other modern technologies, which has helped me strengthen my technical and problem-solving skills. I consider myself a quick learner, a dedicated team player, and someone who enjoys continuously improving both technical and communication abilities. One of my strengths is adaptability, as I can quickly understand new concepts and technologies. I also pay close attention to detail while designing user-friendly applications. My goal is to become a skilled software engineer and contribute to building scalable products that positively impact users. Outside of coding, I enjoy learning about AI technologies, reading tech blogs, and working on side projects that enhance my practical development experience.`


module.exports = {
    resume,
    jobDescription,
    selfDescription
}